version: '3'

name: 'kaizoku'

services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:preview
    environment:
      - TZ=Etc/UTC # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Comment these out if you do not use the flaresolverr container at the bottom of this file
      - FLARESOLVERR_ENABLED=true
      - FLARESOLVERR_URL=http://flaresolverr:8191
    volumes:
      - /mnt/storage/shared/media/manga:/home/suwayomi/.local/share/Tachidesk/downloads
      - /home/house/tachidesk/files:/home/suwayomi/.local/share/Tachidesk      
    ports:
      - "4567:4567"
    restart: on-failure:3
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Etc/UTC # Use TZ database name from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    ports:
      - "8191:8191"
    restart: unless-stopped
  kavita:
    image: jvmilazz0/kavita:latest
    restart: unless-stopped
    volumes:
      - /home/house/kavita:/kavita/config
      - /mnt/storage/shared/media/manga:/manga
    ports:
      - '5000:5000'
