version: '3'

name: 'media'

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/house/qbittorrent/config:/config
      - /mnt/storage/shared/torrents:/downloads
    ports:
      - '8080:8080'
      - '62609:62609'

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/house/jackett/downloads:/downloads
      - /home/house/jackett/config:/config
    ports:
      - '9117:9117'

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/storage/shared/media/tv:/tv
      - /mnt/storage/shared/media/animes:/animes
      - /mnt/storage/shared/media/movies:/movies
      - /home/house/bazarr/appdata/config:/config
    ports:
      - '6767:6767'

  overseerr:
    image: sctx/overseerr
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Bogota
      - PORT=5055
    volumes:
      - /home/home/overseerr/config:/app/config
    ports:
      - '5055:5055'

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    depends_on:
      - flaresolverr
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/house/prowlarr/config:/config
    ports:
      - '9696:9696'

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    volumes:
      - /home/house/flaresolverr/config:/config
    ports:
      - '8191:8191'

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/house/radarr/appdata/config:/config
      - /mnt/storage/shared/torrents:/downloads      
      - /mnt/storage/shared/media/tv:/tv
      - /mnt/storage/shared/media/animes:/animes
      - /mnt/storage/shared/media/movies:/movies
    ports:
      - '7878:7878'

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/house/sonarr/appdata/config:/config
      - /mnt/storage/shared/torrents:/downloads      
      - /mnt/storage/shared/media/tv:/tv
      - /mnt/storage/shared/media/animes:/animes
      - /mnt/storage/shared/media/movies:/movies
    ports:
      - '8989:8989'

  plex:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
      - PUID=1000
      - PGID=1000
      - VA_DRIVER=IHD
      - PLEX_HW_TRANS_MAX=16
    volumes:
      - /home/house/plex/config:/config
      - /home/house/plex/data:/data
      - /home/house/plex/transcode:/transcode
      - /mnt/storage/shared/media:/media
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    network_mode: host
